---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
## Loading following packages. If packages do not exist, install using install.packages().
library("lubridate")
library("dplyr")

unzip("activity.zip")
activity<-read.csv("activity.csv", header = TRUE)

## What is mean total number of steps taken per day?
steps.per.day<-activity %>% 
               group_by(date) %>%
               summarize(Mean=mean(steps, na.rm=TRUE), Total=sum(steps), Median=median(steps, na.rm=TRUE))
total.mean<-mean(mean.steps.per.day$Mean.Steps, na.rm=TRUE)

hist(steps.per.day$Total, main="Total Number Of Steps Taken Each Day", xlab="Number Of Steps")

mean.steps.per.day<-mean(steps.per.day$Total, na.rm=TRUE)
median.steps.per.day<-median(steps.per.day$Total, na.rm=TRUE)

## What is the average daily activity pattern?

daily.activity<-activity %>% 
                group_by(interval) %>% 
                summarise(Average=mean(steps, na.rm=TRUE))

plot(daily.activity, type="l", main="Average Number Of Steps Taken", ylab="Number Of Steps", xlab="Interval")

max.steps.interval<-with(daily.activity, interval[Average==max(Average)])

## Imputing missing values
NA.rows<-sum(is.na(activity))

## Studying the activity dataset we see that there are 8 days missing data at all minute intervals. There are no days that are missing data for partial inverval set. Repleacing missing data with average steps over entire dataset.


new.value<-round(mean(activity$steps, na.rm=TRUE))

new.activity<-activity
new.activity$steps[is.na(new.activity$steps)]<-new.value

new.steps.per.day<-new.activity %>% 
                  group_by(date) %>%
                  summarize(Mean=mean(steps, na.rm=TRUE), Total=sum(steps), Median=median(steps, na.rm=TRUE))

new.total.mean<-mean(mean.steps.per.day$Mean.Steps, na.rm=TRUE)

hist(new.steps.per.day$Total, main="Total Number Of Steps Taken Each Day(Imputed)", xlab="Number Of Steps")

new.mean.steps.per.day<-mean(new.steps.per.day$Total, na.rm=TRUE)
new.median.steps.per.day<-median(new.steps.per.day$Total, na.rm=TRUE)

## Are there differences in activity patterns between weekdays and weekends?

##Date columnn converted to date format using ymd()
activity$date<-ymd(activity$date)